- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - Barratry
  - StarlightCog
  - Cork
  - StarlightExo
  - StarlightFland
  - StarlightHotel
  - Lagan
  - Leth
  - Lobster
  - Manor
  - StarlightOasis
  - StarlightOmega
  - Origin
  - Orwell
  - StarlightReach
  - StarlightSaltern
  - Starboard
  - Kiloton
  - StarlightElkridge
  - Prism
  - StarlightSilica
  - StarlightCluster
  - StarlightBox
# - StarlightMarathon
# - StarlightMeta
# - StarlightPacked
