- type: dungeonConfig
  id: SyndieDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SyndieDungeon
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorDunGen
    width: 5
    tile: FloorShuttleRed

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorShuttleRed
    contents: SyndieDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonEntrance

  - !type:EntranceFlankDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonWindow

  - !type:WallMountDunGen
    tile: FloorShuttleRed
    contents: SyndieDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorShuttleRed
    wall: WallReinforced
    cornerWall: WallReinforced

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entityTable
  id: SyndieDungeonEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: AirlockSyndicateLocked

- type: entityTable
  id: SyndieDungeonWindow
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WallBrick
    - id: LandMineExplosive
    - id: PoweredSmallLight

- type: entityTable
  id: SyndieDungeonWalls
  table: !type:GroupSelector
    children:
    # Posters
    - id: PosterContrabandEnlistGorlex
    - id: PosterLegitEnlist
    - id: PosterContrabandFreeDrone
    - id: PosterContrabandFreeSyndicateEncryptionKey
    - id: PosterContrabandSyndicatePistol

#========================================================================
- type: dungeonConfig
  id: ShipWreckDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - ShipWreck
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

#========================================================================   

# type: dungeonConfig
# id: NoWallArenaPlanetBase
# layers:
# - !type:PrefabDunGen
#   presets:
#   - Arena
#   
# - !type:CorridorDunGen
#   width: 1
#
# - !type:DungeonEntranceDunGen
#   count: 1
#
# - !type:RoomEntranceDunGen
#
# - !type:EntranceFlankDunGen
#
# - !type:BoundaryWallDunGen
#
# - !type:JunctionDunGen
#   width: 1
#
# - !type:JunctionDunGen
#
# - !type:CornerClutterDunGen

#- type: dungeonConfig
#  id: ElderArenaDungeon
#  data:
#    tiles:
#      FallbackTile: FloorAbyss
#    spawnGroups:
#      Window: Nothing
#    whitelists:
#      Rooms:
#        tags:
#        - ElderArena
#  layers:
#  - !type:PrototypeDunGen
#    proto: NoWallArenaPlanetBase

#========================================================================   
- type: dungeonConfig
  id: SovietDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SovietDungeon
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall

  - !type:CorridorDunGen
    width: 5
    tile: FloorConcreteMono

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorConcreteMono
    contents: SovietDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonRoomEntrance

  - !type:EntranceFlankDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWindow

  - !type:WallMountDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorConcreteMono
    wall: WallBrick
    cornerWall: WallBrick

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe

- type: entityTable
  id: SovietDungeonEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: MetalDoor

- type: entityTable
  id: SovietDungeonRoomEntrance
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WoodDoor

- type: entityTable
  id: SovietDungeonWindow
  table: !type:GroupSelector
    children:
    - id: CableApcExtension
    - id: WallBrick
    - id: PoweredSmallLight

- type: entityTable
  id: SovietDungeonWalls
  table: !type:GroupSelector
    children:
    # Posters
    - id: PosterContrabandCommunistState
    - id: PosterContrabandPunchShit
    - id: PosterContrabandRevolt
    - id: PosterContrabandRise
    - id: PosterLegitWorkForAFuture

#========================================================================

- type: dungeonConfig
  id: SovietStrategicResourcesWarehouseDungeon
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - SovietWarehouse
    presets:
    - Arena

  - !type:CorridorDunGen
    width: 5
    tile: FloorConcreteMono

  - !type:DungeonEntranceDunGen
    count: 5
    tile: FloorConcreteMono
    contents: SovietDungeonEntrance

  - !type:RoomEntranceDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonRoomEntrance

  - !type:EntranceFlankDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWindow

  - !type:WallMountDunGen
    tile: FloorConcreteMono
    contents: SovietDungeonWalls

  - !type:BoundaryWallDunGen
    tile: FloorConcreteMono
    wall: WallBrick
    cornerWall: WallBrick

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: BaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe