- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for an document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        Steel: 3
        Manipulator: 1
        Glass: 1
        
- type: entity
  id: OvenMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: oven machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenOven
      stackRequirements:
        Steel: 4
        Glass: 2
        Cable: 10
    - type: Tag
      tags:
      - OvenMachineBoard
      
- type: entity
  id: StoveMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: stove machine board
  components:
    - type: Sprite
      state: service
    - type: MachineBoard
      prototype: KitchenStove
      stackRequirements:
        Steel: 1
        Cable: 5
    - type: Tag
      tags:
      - StoveMachineBoard