- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 57600 #16 hrs
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  canBeAntag: true
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: SurgeonGear
  equipment:
    ears: ClothingHeadsetMedical
  inhand:
    - ClothingBackpackDuffelSurgeryFilled