- type: job
  id: NTNCBlueshield
  name: job-name-ntncblueshield
  description: job-description-ntncblueshield
  playTimeTracker: JobConsortiumBlueShield
  setPreference: false
  startingGear: NTNCBlueShieldGear
  icon: JobIconNTNCBlueShield
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, DeathRattleImplantCentcomm, RadioImplantCentcomm ]

- type: startingGear
  id: NTNCBlueShieldGear
  equipment:
    jumpsuit: ClothingUniformNTNCFatigues
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatBeretBlueShield
    outerClothing: ClothingOuterVestNTNC
    id: NTNCCSPDA
    eyes: ClothingEyesGlassesBlueShield
    ears: ClothingHeadsetAltCommand
    belt: ClothingBeltBlueShieldWebbingFilled
    gloves: ClothingHandsGlovesCombat
    pocket1: WeaponMultiphaseGun
    pocket2: WeaponPistolN1984
  storage:
    back:
    - Flash
    - ClothingMaskGasBSO
