- type: job
  id: NTNCBlueshield
  name: job-name-ntncblueshield
  description: job-description-ntncblueshield
  playTimeTracker: JobConsortiumBlueShield
  setPreference: false
  startingGear: NTNCHardsuitGear
  icon: JobIconNTNCBlueShield
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant, DeathRattleImplantCentcomm, RadioImplantCentcomm ]