- type: job
  id: CentralCommandOperator
  name: job-name-centcomoperator
  description: job-description-centcomoperator
  playTimeTracker: JobCentralCommandOperator
  setPreference: false
  startingGear: CentcomOperatorGear
  icon: "JobIconCentCommOperator"
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CentcomOperatorGear
  equipment:
    jumpsuit: ClothingAltUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesColorBlack
    id: CentCommOperatorPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
    pocket1: BoxFolderBlack
    pocket2: PenCentcom
