- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCentComm"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetCentCom #Starlight
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterSoftsuitCBURN #Starlight
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
    head: ClothingHeadSoftsuitCBURN # Starlight
  storage:
    back:
#    - WeaponShotgunDoubleBarreled Starlight: Replaced with starlight weaponry
#    - BoxShotgunIncendiary
    # Starlight-start: Starlight incendiary weaponry
    - WeaponIK60
    - MagazineBatteryLr30
    - MagazineBatteryLr30
    - MagazineBatteryLr30
    - MagazineBatteryLr30
    # Starlight-end
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
