- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeEnergySniper
  name: LWAP safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergySniper
      amount: 2

- type: entity
  id: LockerSecurityLargeFilled
  suffix: Filled
  parent: LockerSecurityLarge
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.6
      - id: ClothingHeadHelmetBasic
        amount: 2
      - id: ClothingOuterArmorBasic
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHeadsetSecurity
        amount: 2
      - id: ClothingHandsGlovesSecurityRed
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: WeaponMeleeNeedle
        prob: 0.5
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2

- type: entity
  id: LockerBrigmedicLargeFilled
  suffix: Filled
  parent: LockerBrigmedicLarge
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesBrigmedic
        amount: 2
      - id: ClothingEyesHudBrigmedic
        amount: 2
      - id: WeaponDisabler
        amount: 2
      - id: TrackingImplanter
        amount: 4
      - id: ClothingOuterHardsuitBrigmedic
        amount: 2
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretBrigmedic
      - id: ClothingOuterCoatAMG
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingUniformJumpskirtOfLife
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatCorpsman
      - id: ClothingUniformJumpsuitCorpsman
      - id: ClothingUniformJumpskirtCorpsman
      - id: ClothingBeltCorpsmanFilled
      - id: ClothingHandsGlovesBlackNitrile
      - id: ClothingShoesBootsMagSec
        amount: 2
      - id: BedsheetBrigmedicStrange
      - id: BedsheetBrigmedic
      - id: MedkitFilled
        amount: 2
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: MedkitBurnFilled
        prob: 0.7
      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse
        prob: 0.35
      - id: RubberStampBrigmedic
        amount: 2
      - id: PlushieMorgana
      - id: PlushieKiller


- type: entity
  id: LockerWardenLargeFilled
  suffix: Filled
  parent: LockerWardenLarge
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        amount: 2
      - id: WeaponEnergyShotgun
      - id: WeaponDisabler
        amount: 2
      - id: ClothingBeltSecurityFilled
        amount: 2
      - id: Flash
        amount: 2
      - id: ClothingEyesGlassesSecurity
        amount: 2
      - id: ClothingEyesHudSecurity
        amount: 2
      - id: ClothingHandsGlovesCombat
        amount: 2
      - id: ClothingHeadsetSecurityWarden
        amount: 2
      - id: ClothingShoesBootsJack
        amount: 2
      - id: ClothingOuterCoatWarden
        amount: 2
      - id: ClothingOuterWinterWarden
        amount: 2
      - id: RubberStampWarden
        amount: 2
      - id: DoorRemoteArmory
        amount: 2
      - id: HoloprojectorSecurity
        amount: 2
      - id: BookSpaceLaw
        amount: 2
      - id: ClothingBackpackElectropack
        amount: 4
      - id: RemoteSignaller
        amount: 4
      - id: Binoculars
        amount: 2
