- type: job
  id: Assistant
  name: job-name-assistant
  description: job-description-assistant
  playTimeTracker: JobPassenger
  startingGear: AssistantGear
  icon: "JobIconAssistant"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: job # Just ignore it. It’s a database workaround.
  id: Passenger
  hidden: true
  name: job-name-assistant
  description: job-description-assistant
  playTimeTracker: JobAssistant 
  startingGear: AssistantGear
  icon: "JobIconAssistant"
  supervisors: job-supervisors-everyone
  access:
  - Maintenance

- type: startingGear
  id: AssistantGear
  equipment:
    id: AssistantPDA
    ears: ClothingHeadsetAssistant
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
