## Static recipes

- type: latheRecipePack
  id: StarlightSecurityEquipmentStatic
  recipes:
  - ClothingEyesHudSecurity
  - ForensicPad
  - Handcuffs
  - TargetClown
  - TargetHuman
  - TargetSyndicate
  - Zipties

# Practice ammo/mags and practice weapons
- type: latheRecipePack
  id: StarlightSecurityPracticeStatic
  recipes:
  - BoxShotgunPractice
  - MagazineBoxLightRiflePractice
  - MagazineBoxMagnumPractice
  - MagazineBoxPistolPractice
  - MagazineBoxCaselessRiflePractice
  - MagazineBoxRiflePractice
  - WeaponDisablerPractice
  - WeaponLaserCarbinePractice
  - WeaponFlareGunSecurity

# Shared between secfab and emagged autolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoStatic
  recipes:
######################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleSP
  - MagazineBoxLightRifleHP
  - MagazineBoxLightRifleFMJ
# Magnum
  - MagazineBoxMagnumSP
  - MagazineBoxMagnumHP
  - MagazineBoxMagnumFMJ
# Pistol
  - MagazineBoxCaselessRifle
  - MagazineBoxCaselessRifleRubber
  - MagazineBoxPistolSP
  - MagazineBoxPistolHP
  - MagazineBoxPistolFMJ
  - MagazineBoxPistol40SP
  - MagazineBoxPistol40HP
  - MagazineBoxPistol40FMJ
# Rifle
  - MagazineBoxRifleSP
  - MagazineBoxRifleHP
  - MagazineBoxRifleFMJ
# Shotgun
  - BoxLethalshot
  - BoxShotgunSlug
  - BoxShellTranquilizer
#####################MAGAZINE#######################
# LMG
  - LightRifleHeavyMagazineSP
  - LightRifleHeavyMagazineHP
  - LightRifleHeavyMagazineFMJ
  - LightRifleHeavyMagazineEmpty
# Light Rifle
  - MagazineLightRifleSP
  - MagazineLightRifleHP
  - MagazineLightRifleFMJ
  - MagazineLightRifleMaxim
  - SpeedLoaderLightRifle
  - MagazineLightRifleEmpty
# Magnum
  - SpeedLoaderMagnumSP
  - SpeedLoaderMagnumHP
  - SpeedLoaderMagnumFMJ
  - MagazineMagnum
  - MagazineMagnumRifleSP
  - MagazineMagnumEmpty
  - SpeedLoaderMagnumEmpty
# Pistol
  - MagazinePistolCaselessRifle
  - MagazineCaselessRifleRubber
  - MagazinePistolSP
  - MagazinePistolHP
  - MagazinePistolFMJ
  - MagazinePistolEmpty
  - MagazinePistol40SP
  - MagazinePistol40HP
  - MagazinePistol40FMJ
  - MagazinePistol40Empty
# SMG
  - MagazinePistolSubMachineGunSP
  - MagazinePistolSubMachineGunHP
  - MagazinePistolSubMachineGunFMJ
  - MagazinePistolSubMachineGunEmpty
  - MagazinePistolSubMachineGunTopMounted
  - MagazinePistolSubMachineGunTopMountedEmpty
  - MagazinePistolSubMachineGunUzi
  - MagazinePistolSubMachineGunPPSH
# Rifle
  - MagazineRifleSP
  - MagazineRifleHP
  - MagazineRifleFMJ
  - MagazineRifleEmpty
# Shotgun
  - MagazineShotgun
  - MagazineShotgunEmpty
  - MagazineShotgunSlug
  
  - SpeedLoaderMagnumBasic
  - SpeedLoaderShotgunEmpty
  - SpeedLoaderShotgunSlug
  - SpeedLoaderShotgunBeanbag
####################################################

- type: latheRecipePack
  id: StarlightSecurityEmagWeaponsStatic
  recipes:
  - BoxLethalshot
  - BoxShotgunSlug
  - CombatKnife
  - RiotShield

## Dynamic recipes

- type: latheRecipePack
  id: StarlightDefenseStatic
  recipes:
  - EnergyDomeTurtle

- type: latheRecipePack
  id: StarlightSecurityEquipment
  recipes:
  - ClothingBackpackElectropack
  - HoloprojectorSecurity
  - PortableRecharger
  - PowerCageHigh
  - PowerCageMedium
  - PowerCageSmall
  - TelescopicShield

- type: latheRecipePack
  id: StarlightSecurityBoards
  recipes:
  - ShuttleGunDusterCircuitboard
  - ShuttleGunFriendshipCircuitboard
  - ShuttleGunPerforatorCircuitboard
  - ShuttleGunSvalinnMachineGunCircuitboard
  - ScanGateMachineCircuitboard

- type: latheRecipePack
  parent:
  - ScienceExplosives # sec gets everything for modular grenade making that sci does
  id: StarlightSecurityExplosives
  recipes:
  - ExplosivePayload
  - GrenadeBlast
  - GrenadeEMP
  - GrenadeFlash
  - MagazineGrenadeEmpty

# Shared between secfab and emagged protolathe
- type: latheRecipePack
  id: StarlightSecurityAmmoDynamic
  recipes:
#####################BOX#######################
# Light Rifle
  - MagazineBoxLightRifleRubber
  - MagazineBoxLightRifleIncendiary
  - MagazineBoxLightRifleUranium
  - MagazineBoxLightRifleAP
# Magnum
  - MagazineBoxMagnumRubber
  - MagazineBoxMagnumIncendiary
  - MagazineBoxMagnumUranium
  - MagazineBoxMagnumAP
# Pistol
  - MagazineBoxPistolRubber
  - MagazineBoxPistolIncendiary
  - MagazineBoxPistolUranium
  - MagazineBoxPistolAP
  - MagazineBoxPistol40AP
# Rifle
  - MagazineBoxRifleRubber
  - MagazineBoxRifleIncendiary
  - MagazineBoxRifleUranium
  - MagazineBoxRifleAP
# Shotgun
  - BoxBeanbag
  - BoxShotgunIncendiary
  - BoxShotgunUranium
  - BoxShellTranquilizer
#####################MAGAZINE#######################
# LMG
  - LightRifleHeavyMagazineIncendiary
  - LightRifleHeavyMagazineUranium
  - LightRifleHeavyMagazineAP
# Light Rifle
  - MagazineLightRifleIncendiary
  - MagazineLightRifleUranium
  - MagazineLightRifleAP
# Magnum
  - SpeedLoaderMagnumIncendiary
  - SpeedLoaderMagnumUranium
  - SpeedLoaderMagnumAP
# Pistol
  - MagazinePistolIncendiary
  - MagazinePistolUranium
  - MagazinePistolAP
  - MagazinePistol40AP
# SMG
  - MagazinePistolSubMachineGunIncendiary
  - MagazinePistolSubMachineGunUranium
  - MagazinePistolSubMachineGunAP
# Rifle
  - MagazineRifleIncendiary
  - MagazineRifleUranium
  - MagazineRifleAP
# Shotgun
  - MagazineShotgunBeanbag
  - MagazineShotgunIncendiary
  - SpeedLoaderShotgunIncendiary
  - SpeedLoaderShotgunUranium
# Grenade
  - MagazineGrenadeEmpty
#####################CARTRIDGE######################
# Light Rifle
  - CartridgeLightRifleRubber
# Magnum
  - CartridgeMagnumRubber
# Pistol
  - CartridgePistolRubber
# Rifle
  - CartridgeRifleRubber
####################################################

- type: latheRecipePack
  id: StarlightSecurityWeapons
  recipes:
  - Truncheon
  - WeaponAdvancedLaser
  - WeaponLaserCannon
  - WeaponLaserCarbine
  - WeaponXrayCannon
  - WeaponIonRifle
  - WeaponIonCarbine
  - WeaponDecloner
  - WeaponLaserImmolator
  - WeaponLaserSvalinn
  - WeaponTemperatureGun

- type: latheRecipePack
  id: StarlightSecurityMechsWeapons
  recipes:
  - WeaponMechCombatMissileRack8
  - WeaponMechCombatShotgun
  - WeaponMechCombatShotgunIncendiary
  - WeaponMechCombatUltraRifle

- type: latheRecipePack
  id: StarlightSecurityMechs
  recipes:
  - GygaxHarness
  - GygaxArmor
  - GygaxHead
  - GygaxLArm
  - GygaxLLeg
  - GygaxRArm
  - GygaxRLeg
  - GygaxCentralElectronics
  - GygaxPeripheralsElectronics
  - GygaxTargetingElectronics

  - DurandHarness
  - DurandArmor
  - DurandHead
  - DurandLArm
  - DurandLLeg
  - DurandRArm
  - DurandRLeg
  - DurandCentralElectronics
  - DurandPeripheralsElectronics
  - DurandTargetingElectronics

- type: latheRecipePack
  id: SecurityCyberLimbs
  recipes:
  - LeftArmCyberBulwark
  - RightArmCyberBulwark
