- type: entity
  id: BaseStationCryoTeleportation
  abstract: true
  components:
  - type: StationCryoTeleportation
  
- type: entity
  id: BaseStationAlertArmories
  abstract: true
  components:
    - type: AlertArmoryStation
      shuttles:
        gamma:
          shuttle: /Maps/_Starlight/Shuttles/CC-NT/GammaWeaponry.yml
          announcement: announcement-gamma-armory
        psi:
          shuttle: /Maps/_Starlight/Shuttles/CC-NT/PsiArmory.yml
          announcement: announcement-psi-armory
          announcementColor: "#2288ff"