# No idea why it's in sci but we ball.
# Why is this one file?
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
  - !type:RoleTimeRequirement
    role: JobBorg
    time: 18000  # 5 hrs
  canBeAntag: false
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  jobPreviewEntity: PlayerStationAiPreview
  # Cosmatic Drift: AIs spawn as non-humanoids, so skip loading character records for them.
  special:
  - !type:AddComponentSpecial
    components:
    - type: SkipLoadingCharacterRecords
  applyTraits: false

- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgBattery
  # Cosmatic Drift: Cyborg shells do not use humanoid profiles, so avoid seeding records.
  special:
  - !type:AddComponentSpecial
    components:
    - type: SkipLoadingCharacterRecords
  applyTraits: false
