# The primary role types are referenced by RP Rules, and were specified based on head admin input.
# Do not create new ones without discussion.
# You probably want a Subtype instead, anyway. Use MindRoleComponent.Subtype

# Any new primary role types must be listed in RoleTypes.xml

# If you change/add a color here, also change it in role-types.ftl!

- type: roleType
  id: Neutral
  name: role-type-central-command-aligned-name # DOTS - Pending rename from all instances of "Central Command" to "Corporate Aligned"
  color: '#00b600'
  symbol: "🗡" # Should never be antag, but just in case.