- type: Salaries
  id: standart
  jobs:
    Captain: 150
    HeadOfPersonnel: 130
    HeadOfSecurity: 145
    ChiefEngineer: 140
    ResearchDirector: 130
    ChiefMedicalOfficer: 135
    Quartermaster: 120

    BlueShield: 110
    NanoTrasenRepresentative: 165

    Chemist: 90
    Paramedic: 50
    MedicalDoctor: 58
    MedicalIntern: 23
    Surgeon: 90

    AtmosphericTechnician: 90
    StationEngineer: 54
    TechnicalAssistant: 23

    Warden: 90
    Detective: 80
    Brigmedic: 73
    SecurityOfficer: 64
    SecurityCadet: 23

    StationAi: 155
    Borg: 85

    Chaplain: 50
    Chef: 50
    Janitor: 30
    Botanist: 50
    Librarian: 50
    Musician: 40
    Bartender: 50
    Mime: 30
    Clown: 30
    ServiceWorker: 23
    Assistant: 15

    Scientist: 65
    Roboticist: 56
    ResearchAssistant: 23

    SalvageSpecialist: 60
    MiningSpecialist: 60
    CargoTechnician: 45
    MailTech: 55

    Lawyer: 55
    IAA: 76
    Magistrate: 176

    Visitor: 0
