- type: antag
  id: Changeling
  name: roles-antag-changeling-name
  antagonist: true
  setPreference: true
  objective: roles-antag-changeling-description
  guides: [ Changelings ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 10800 # 3h
