- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#ff178b"
  weight: -10
  roles:
  - Magistrate
  - IAA
  
- type: department
  id: Representives
  name: department-Representives
  description: department-Representives-description
  color: "#05255D"
  roles:
  - BlueShield
  - Magistrate
  - NanoTrasenRepresentative
  primary: false
  weight: 50
