name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested, opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Awaiting Changes"
