name: Publish

concurrency:
  group: publish
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Install OS deps
        run: sudo apt-get install -y python3-paramiko python3-lxml

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fetch all tags (RobustToolbox)
        run: |
          cd RobustToolbox
          git fetch --all --tags

      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: dotnet restore
        run: dotnet restore

      - name: Build Packaging
        run: dotnet build Content.Packaging -c Release --no-restore /m

      - name: Package server
        run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

      - name: Package client
        run: dotnet run --project Content.Packaging client --no-wipe-release

      - name: Publish version
        run: Tools/publish_multi_request.py
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

  update-changelog:
    name: Publish Changelogs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        env:
          ACTIONS_SSH_KEY: ${{ secrets.ACTIONS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$ACTIONS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -T git@github.com || exit 0

      - name: Publish changelog (Discord)
        continue-on-error: true
        run: Tools/actions_changelogs_since_last_run.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit & Push sent changelogs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Resources/Changelog/ChangelogStarlight.yml Tools/changelogs/sent_changelog_ids.yml
          git commit -m "Update sent changelogs [skip ci]"
          git push git@github.com:${{ github.repository }} HEAD:Starlight

      - name: Publish changelog (RSS)
        continue-on-error: true
        run: Tools/actions_changelog_rss.py
        env:
          CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}
