- type: job
  id: MailTech
  name: job-name-mailtech
  description: job-description-mailtech
  playTimeTracker: JobMailTech
  startingGear: MailTechGear
  icon: "JobIconMailTech"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: MailTechGear
  equipment:
    id: MailPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
  storage:
    back:
    - MailTrolleyFlatpack
    - Multitool #maybe not a good idea? idk makes unpacking it quick

- type: chameleonOutfit
  id: MailTechChameleonOutfit
  job: MailTech
  equipment:
    head: ClothingHeadHatCargosoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterCargo
    neck: ClothingNeckScarfStripedBrown
    gloves: ClothingHandsGlovesFingerless
