- type: job
  id: MailTech
  name: job-name-mailtech
  description: job-description-mailtech
  playTimeTracker: JobMailTech
  requirements:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 18000 # 5 hours
  startingGear: MailTechGear
  icon: "JobIconMailTech"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: BoxCardboard

- type: startingGear
  id: MailTechGear
  equipment:
    id: MailPDA
    ears: ClothingHeadsetCargo
    belt: MailBag
  storage:
    back:
    - MailTrolleyFlatpack
    - Multitool #maybe not a good idea? idk makes unpacking it quick
