- type: job
  id: MiningSpecialist
  name: job-name-miningspec
  description: job-description-miningspec
  playTimeTracker: JobMiningSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: Cargo
    time: 10800 # 3 hrs
  - !type:OverallPlaytimeRequirement
    time: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: MiningSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage #DOTS - replace with "Mining" -- but it might break their access to all current doors.
  - Maintenance
  - External

- type: startingGear
  id: MiningSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMiningSpecialist
    id: MiningPDA # DOTS - verify that the new "mining" access actually applies to the mining id card?
    ears: ClothingHeadsetMining
    #storage:
    #back:
    #- Stuff
