- type: job
  id: SalvageLead
  name: job-name-salvagelead
  description: job-description-salvagelead
  playTimeTracker: JobSalvageLead
  requirements:
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 # 10 hours
  icon: "JobIconSalvageLead"
  startingGear: SalvageLeadGear
  supervisors: job-supervisors-qm
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SalvageLeadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageLead
    id: SalvageLeadPDA
    ears: ClothingHeadsetSalvageLead
  #storage:
    #back:
    #- Stuff
